# Generated by Django 4.2.8 on 2023-12-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField(auto_now=True)),
                ('endDate', models.DateField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
