# Generated by Django 4.2.8 on 2023-12-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twalker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmembers',
            name='startDate',
            field=models.DateField(),
        ),
    ]
